const fs=require('fs'),path=require('path'),os=require('os');
const {execFileSync,spawn}=require('child_process');
const ROOT=__dirname, UP=path.join(os.tmpdir(),'solana-trading-bot-v3-paper'), STATE=path.join(ROOT,'data','paper-state.json');
const REPO='https://github.com/wwwwwwworld/solana-trading-bot-v3.git', COMMIT='ee65514efe385a7d3f427a0130d4e2a1a2383a82';
const runMinutes=Number(process.env.PAPER_RUN_MINUTES||330);
const sh=(c,a,cwd)=>execFileSync(c,a,{cwd,stdio:'inherit',env:process.env});
const paperTs=()=>String.raw`// @ts-nocheck
import fs from 'fs';import path from 'path';import {Liquidity,TokenAmount} from '@raydium-io/raydium-sdk';import {logger} from './helpers';
const stateFile=process.env.PAPER_STATE_FILE||path.join(process.cwd(),'data','paper-state.json'),initialUsd=Number(process.env.PAPER_INITIAL_USD||100),tgToken=process.env.TELEGRAM_BOT_TOKEN||'',tgChat=process.env.TELEGRAM_CHAT_ID||'';
interface Pos{mint:string;amount:number;costQuote:number;openedAt:number} interface Trade{id:number;side:'BUY'|'SELL';mint:string;amount:number;quote:number;price:number;pnl:number;reason:string;at:string} interface State{version:1;initializedAt:string;initialUsd:number;initialSolUsd:number;initialQuote:number;cashQuote:number;realizedPnlQuote:number;trades:Trade[];positions:Record<string,Pos>;nextTradeId:number}
const n=(x:any)=>Number.parseFloat(String(x)),m=(x:number)=>Number.isFinite(x)?x.toFixed(8):'0';
async function solUsd(){for(const u of ['https://api.coingecko.com/api/v3/simple/price?ids=solana&vs_currencies=usd','https://api.binance.com/api/v3/ticker/price?symbol=SOLUSDT'])try{const r=await fetch(u);if(r.ok){const j:any=await r.json(),p=j?.solana?.usd??j?.price;if(Number(p)>0)return Number(p)}}catch(_){}throw Error('SOL/USD price unavailable; refusing to invent conversion')}
async function tg(text:string){if(!tgToken||!tgChat)return;try{await fetch('https://api.telegram.org/bot'+tgToken+'/sendMessage',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:tgChat,text})})}catch(e){logger.warn({error:e},'Telegram notification failed')}}
function read():State|null{try{return JSON.parse(fs.readFileSync(stateFile,'utf8'))}catch(_){return null}} function save(s:State){fs.mkdirSync(path.dirname(stateFile),{recursive:true});const t=stateFile+'.tmp';fs.writeFileSync(t,JSON.stringify(s,null,2));fs.renameSync(t,stateFile)}
class PT{state:Promise<State>;constructor(){this.state=this.load()}async load(){const e=read();if(e)return e;const p=await solUsd(),q=process.env.QUOTE_MINT==='USDC'?initialUsd:initialUsd/p,s:State={version:1,initializedAt:new Date().toISOString(),initialUsd,initialSolUsd:p,initialQuote:q,cashQuote:q,realizedPnlQuote:0,trades:[],positions:{},nextTradeId:1};save(s);await tg('🟢 PAPER SESSION START\nCapital: $'+initialUsd.toFixed(2)+'\nSOL/USD: $'+p.toFixed(2)+'\nVirtual quote capital: '+m(q));return s}
async execute(a:any){const s=await this.state,mint=a.poolKeys.baseMint.toString(),qin=n(a.amountIn.toFixed()),qout=n(a.computedAmountOut.toFixed());if(a.direction==='buy'){if(s.cashQuote<qin)return{confirmed:false,error:'insufficient virtual capital'};const o=s.positions[mint],amt=(o?.amount||0)+qout,cost=(o?.costQuote||0)+qin;s.cashQuote-=qin;s.positions[mint]={mint,amount:amt,costQuote:cost,openedAt:o?.openedAt||Date.now()};s.trades.push({id:s.nextTradeId++,side:'BUY',mint,amount:qout,quote:qin,price:qin/qout,pnl:0,reason:'original strategy BUY',at:new Date().toISOString()});save(s);await tg('🟢 PAPER BUY\nMint: '+mint+'\nSize: '+m(qout)+'\nCost: '+m(qin)+'\nCash: '+m(s.cashQuote)+'\nReason: original strategy BUY');if(a.config.autoSell)await this.watch(a,s.positions[mint]);return{confirmed:true,signature:'PAPER-'+Date.now()}}return this.close(s,mint,qin,'original strategy SELL')}
async watch(a:any,p:Pos){const intv=Number(a.config.priceCheckInterval),dur=Number(a.config.priceCheckDuration);if(!intv||!dur){await this.sellAt(a,p,'price checks disabled / immediate auto-sell');return}const end=Date.now()+dur;while(Date.now()<end){try{const pi=await Liquidity.fetchInfo({connection:a.connection,poolKeys:a.poolKeys}),ti=new TokenAmount(a.tokenIn,String(Math.floor(p.amount*Math.pow(10,a.tokenIn.decimals))),false),q=Liquidity.computeAmountOut({poolKeys:a.poolKeys,poolInfo:pi,amountIn:ti,currencyOut:a.config.quoteToken,slippage:a.sellSlippage}).amountOut,cur=n(q.toFixed()),tp=p.costQuote*(1+Number(a.config.takeProfit)/100),sl=p.costQuote*(1-Number(a.config.stopLoss)/100);if(cur>=tp){await this.sellAt(a,p,'TAKE_PROFIT');return}if(cur<=sl){await this.sellAt(a,p,'STOP_LOSS');return}}catch(e){logger.debug({error:e,mint:p.mint},'Paper price check failed')}await new Promise(r=>setTimeout(r,intv))}await this.sellAt(a,p,'PRICE_CHECK_TIMEOUT')}
async sellAt(a:any,p:Pos,reason:string){try{const pi=await Liquidity.fetchInfo({connection:a.connection,poolKeys:a.poolKeys}),ti=new TokenAmount(a.tokenIn,String(Math.floor(p.amount*Math.pow(10,a.tokenIn.decimals))),false),q=Liquidity.computeAmountOut({poolKeys:a.poolKeys,poolInfo:pi,amountIn:ti,currencyOut:a.config.quoteToken,slippage:a.sellSlippage}).amountOut;await this.close(await this.state,p.mint,n(q.toFixed()),reason)}catch(e){logger.warn({error:e,mint:p.mint},'Paper auto-sell failed; position remains persisted')}}
async close(s:State,mint:string,q:number,reason:string){const p=s.positions[mint];if(!p)return{confirmed:false,error:'paper position not found'};const pnl=q-p.costQuote;s.cashQuote+=q;s.realizedPnlQuote+=pnl;s.trades.push({id:s.nextTradeId++,side:'SELL',mint,amount:p.amount,quote:q,price:q/p.amount,pnl,reason,at:new Date().toISOString()});delete s.positions[mint];save(s);const sells=s.trades.filter((x:Trade)=>x.side==='SELL'),w=sells.filter((x:Trade)=>x.pnl>0).length,l=sells.length-w;await tg((pnl>=0?'🟢':'🔴')+' PAPER SELL\nMint: '+mint+'\nExit: '+m(q)+'\nP&L: '+m(pnl)+'\nCash: '+m(s.cashQuote)+'\nReason: '+reason+'\nWins/Losses: '+w+'/'+l);return{confirmed:true,signature:'PAPER-'+Date.now()}}
}export const paperTrader=new PT();`;
function patch(){const c=path.join(UP,'helpers/constants.ts');let x=fs.readFileSync(c,'utf8');x=x.replace("export const PRIVATE_KEY = retrieveEnvVariable('PRIVATE_KEY', logger);","export const PAPER_MODE = (process.env.PAPER_MODE || 'true') === 'true';\nexport const PRIVATE_KEY = PAPER_MODE ? '' : retrieveEnvVariable('PRIVATE_KEY', logger);");fs.writeFileSync(c,x);
const b=path.join(UP,'bot.ts');let y=fs.readFileSync(b,'utf8');y=y.replace("import { JitoTransactionExecutor } from './transactions/jito-rpc-transaction-executor';","import { JitoTransactionExecutor } from './transactions/jito-rpc-transaction-executor';\nimport { paperTrader } from './paper-trader';");y=y.replace("  async validate() {\n    try {","  async validate() {\n    if (process.env.PAPER_MODE === 'true') return true;\n    try {");const anchor="    const latestBlockhash = await this.connection.getLatestBlockhash();";const replacement="    if (process.env.PAPER_MODE === 'true') return paperTrader.execute({ direction, poolKeys, tokenIn, tokenOut, amountIn, computedAmountOut: computedAmountOut.amountOut, config: this.config, connection: this.connection, sellSlippage: slippagePercent });\n\n"+anchor;if(!y.includes(anchor))throw Error('upstream swap anchor missing');y=y.replace(anchor,replacement);fs.writeFileSync(b,y);
const i=path.join(UP,'index.ts');let z=fs.readFileSync(i,'utf8');z=z.replace("  const wallet = getWallet(PRIVATE_KEY.trim());","  const wallet = PAPER_MODE ? Keypair.generate() : getWallet(PRIVATE_KEY.trim());");z=z.replace("  CONSECUTIVE_FILTER_MATCHES,","  CONSECUTIVE_FILTER_MATCHES,\n  PAPER_MODE,");z=z.replace("  logger.info('Bot is starting...');","  logger.info('Bot is starting...');\n  if (PAPER_MODE) logger.warn('PAPER MODE ENABLED: real transaction submission is hard-blocked.');");fs.writeFileSync(i,z);fs.writeFileSync(path.join(UP,'paper-trader.ts'),paperTs())}
async function main(){if(String(process.env.PAPER_MODE||'true')!=='true')throw Error('Safety stop: PAPER_MODE must be true');process.env.PAPER_STATE_FILE=STATE;fs.rmSync(UP,{recursive:true,force:true});sh('git',['clone','--depth','1',REPO,UP]);sh('git',['fetch','--depth','1','origin',COMMIT],UP);sh('git',['checkout',COMMIT],UP);fs.mkdirSync(path.dirname(STATE),{recursive:true});if(fs.existsSync(STATE)){fs.mkdirSync(path.join(UP,'data'),{recursive:true});fs.copyFileSync(STATE,path.join(UP,'data','paper-state.json'))}patch();sh('npm',['install','--no-audit','--no-fund'],UP);sh('npm',['run','tsc'],UP);const env={...process.env,PAPER_MODE:'true',PAPER_STATE_FILE:STATE};const child=spawn('npm',['start'],{cwd:UP,env,stdio:'inherit'});const stop=()=>{try{child.kill('SIGTERM')}catch(_){}};process.on('SIGTERM',stop);process.on('SIGINT',stop);const timer=setTimeout(stop,runMinutes*60000);const code=await new Promise(r=>child.on('exit',c=>r(c??0)));clearTimeout(timer);const s=path.join(UP,'data','paper-state.json');if(fs.existsSync(s))fs.copyFileSync(s,STATE);process.exit(Number(code)===0?0:1)}main().catch(e=>{console.error(e);process.exit(1)});